"""empty message

Revision ID: 6b25e9e3ffcc
Revises: d3da964a5940
Create Date: 2020-07-04 18:51:29.740576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b25e9e3ffcc'
down_revision = 'd3da964a5940'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dy_name', sa.String(length=64), nullable=True),
    sa.Column('dy_id', sa.Integer(), nullable=True),
    sa.Column('dy_daoyan', sa.String(length=64), nullable=True),
    sa.Column('dy_zhuyan', sa.String(length=256), nullable=True),
    sa.Column('by_type', sa.String(length=64), nullable=True),
    sa.Column('dy_country', sa.String(length=64), nullable=True),
    sa.Column('dy_yuyan', sa.String(length=64), nullable=True),
    sa.Column('dy_pianchang', sa.Integer(), nullable=True),
    sa.Column('dy_riqi', sa.DateTime(), nullable=True),
    sa.Column('dy_img', sa.String(length=256), nullable=True),
    sa.Column('dy_desc', sa.String(length=1248), nullable=True),
    sa.Column('dy_xiazai', sa.String(length=128), nullable=True),
    sa.Column('flag', sa.Boolean(), nullable=True),
    sa.Column('is_del', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dy')
    # ### end Alembic commands ###
