"""empty message

Revision ID: d8120c10e2fe
Revises: 05056d865cd0
Create Date: 2020-07-01 01:27:23.349992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8120c10e2fe'
down_revision = '05056d865cd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('let_szm',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('let_szm', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('let_szm')
    )
    op.create_table('city_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('let_szm_id', sa.Integer(), nullable=True),
    sa.Column('c_id', sa.Integer(), nullable=True),
    sa.Column('c_parent_id', sa.Integer(), nullable=True),
    sa.Column('c_name', sa.String(length=16), nullable=True),
    sa.Column('c_sitycode', sa.Integer(), nullable=True),
    sa.Column('c_py', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['let_szm_id'], ['let_szm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('city_model')
    op.drop_table('let_szm')
    # ### end Alembic commands ###
